# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your awesome title
name: Jekyll Start
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://localhost:4000" # the base hostname & protocol for your site
url: http://sepuedecongelar.com/
description: > # this means to ignore newlines until "keywords:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
keywords: jekyll, bootstrap, blogging, github pages, jekyll and bootstrap, seo, font awesome
favicon: img/favicon.png
image: img/jekyll-start.png
permalink: /:title


#Adsense code
adsense:

#Site Stats
google_analytics:

#Google Search console Verification
searchconsole_verification:

#Bing Webmaster tools Verification
bing_verification:


#Comments
disqus:

#Facebook
#App ID
facebook_app:
facebook_adminid:

socialmedia:
  facebook: jekyllstart
  twitter: jekyllstart
  googleplus: jekyllstart
  instagram: jekyllstart
  youtube: jekyllstart


# Build settings
markdown: kramdown

#
include: ['_pages', '_amp']
