# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Se puede Congelar
name: Se puede Congelar
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://localhost:4000" # the base hostname & protocol for your site
url: https://sepuedecongelar.com
description: > # this means to ignore newlines until "keywords:"
  Se puede congelar? Te ayudamos a saber como congelar tu comida favorita. Descubre los secretos para frizar comida y como hacerlo.
  Sepuedecongelar.com se dedica a darle la mejor respuesta sobre congelación de alimentos.
keywords: se puede congelar, se puede frizar, como congelar, como congelar comida, como frizar la comida, freezer, congelador, congelar frutillas
favicon: img/favicon.png
image: img/jekyll-start.png
permalink: /:title


#Adsense code
adsense:
   client: ca-pub-7033627990045927
   slot: 7248228437

#Site Stats
google_analytics: UA-1336963-20

#Google Search console Verification
searchconsole_verification: Yw128oibg1OmYhqgNoKiqWcgFSjW89m1EWk6ZoVD98s

#Bing Webmaster tools Verification
bing_verification: C41371E1ABEAE7BCC0EE15AF51B82D47


#Comments
disqus:

#Facebook
#App ID
facebook_app:
facebook_adminid:

#socialmedia:
#  facebook: sepuedecongelar
#  twitter: sepuedecongelar
#  googleplus: sepuedecongelar
#  instagram: sepuedecongelar
#  youtube: sepuedecongelar

#Paginate settings
paginate: 5
paginate_path: '/page:num/'


# Build settings
markdown: kramdown

#
include: ['_pages', '_amp']

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

#Plugins
gems: [jekyll-paginate, jekyll-redirect-from]
